version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: uptime-go
    main: ./main.go
    binary: uptime-go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X uptime-go/cmd.VERSION={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^Merge"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w,)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w,)]*:+.*$"
      order: 1
    - title: 'Refactor'
      regexp: "^.*refactor[(\\w,)]*:+.*$"
      order: 3
    - title: Others
      order: 999

release:
  draft: false
  github:
    owner: genbucyber
    name: uptime-go